Add home page
RCDD-202110-TUR-BEW/backend-capstone-turkey-paying-it-forward pull request #42
Opened 2022-02-20 21:38 UTC by mehmetfatiherdem

closes #30

2022-02-21 08:58 UTC, Shrreya commented
@Peri7at Can you review this PR today? I'll add my review after yours.

2022-02-21 09:11 UTC, Shrreya commented
@mehmetfatiherdem Can you add a screenshot of the home page in the PR description?

2022-02-21 15:07 UTC, Peri7at commented
Great job @mehmetfatiherdem.
It looks good overall though in my PC, homepage looks like this.. I don't know if it is in our scope to arrange homepage according to screen sizes..
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91065358/154980479-e05c3ec3-8010-4dcb-8afd-0dd18d861fe6.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91065358/154980959-432abdb9-d950-4ca1-b8ee-1a85f9b3ef32.png">
![5DC0429F-27B0-45A4-9DBE-A2BBDE9D96F8_1_102_o](https://user-images.githubusercontent.com/91065358/154981392-7e0527c9-e11e-4f9a-b620-9ce4c15cc17c.jpeg)

2022-02-21 15:15 UTC, Peri7at reviewed
Can you make same right and left margins for all sections?

2022-02-21 15:28 UTC, Peri7at commented
I suggest to change logo for the following photo, what do you think?
![people-circle](https://user-images.githubusercontent.com/91065358/154984832-dc3ee5aa-f023-4074-acb9-a8e4314a72be.jpg)

2022-02-21 15:40 UTC, AmmarBaki2 commented
> I suggest to change logo for the following photo, what do you think? ![people-circle](https://user-images.githubusercontent.com/91065358/154984832-dc3ee5aa-f023-4074-acb9-a8e4314a72be.jpg)

It looks great 👍

2022-02-21 15:46 UTC, mehmetfatiherdem commented
> I suggest to change logo for the following photo, what do you think? ![people-circle](https://user-images.githubusercontent.com/91065358/154984832-dc3ee5aa-f023-4074-acb9-a8e4314a72be.jpg)

sure we can use it :+1:

2022-02-21 15:47 UTC, mehmetfatiherdem commented
> Great job @mehmetfatiherdem. It looks good overall though in my PC, homepage looks like this.. I don't know if it is in our scope to arrange homepage according to screen sizes.. <img alt="image" width="1440" src="https://user-images.githubusercontent.com/91065358/154980479-e05c3ec3-8010-4dcb-8afd-0dd18d861fe6.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/91065358/154980959-432abdb9-d950-4ca1-b8ee-1a85f9b3ef32.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/91065358/154981673-33acca79-eb80-4844-9292-c99e4c767b4e.png">

Yes, I think it is not that responsive :sweat_smile:.

2022-02-21 15:47 UTC, mehmetfatiherdem commented
> Can you make same right and left margins for all sections?

I can try that :+1:

2022-02-21 18:12 UTC, Peri7at approved these changes

2022-02-21 21:08 UTC, Peri7at commented on src/public/css/home.css
>  }
Could you add  the same right and left margins to overview also. All sections look aligned now beside overview section.

2022-02-22 16:58 UTC, mehmetfatiherdem commented
Could you review this PR @Shrreya?

2022-02-23 16:49 UTC, Shrreya requested changes
@mehmetfatiherdem I'm noting down all changes here below.

1. Why is there a screenshot of the API docs? That's not required, once the swagger docs are merged you can just link the navigation item "API Documentation" to the swagger docs route.
2. The screenshots for designs are not looking good. Can you use the Figma embed links instead? Then users can actually move around and interact with the design diagrams?
3. Can you mark my comments on Figma as resolved? Then my "S" bubbles won't show on your designs.
4. Remove the sign in and sign up buttons from the navigation header. Users will authenticate from the swagger docs.
5. Let's use a different color other than black for titles like "Overview", "Items", "Requests" and so on. I think the green color of the header bar can be used.
6. Reduce the font-weight of the paragraph texts. Right now everything seems to be in bold text.
7. I think you can mention a few more technologies like ExpressJS, ESLint, Prettier, Husky, Jest, AWS, Nginx. Be creative and think about what other cool technologies were used.
8. You can show team members in 2 rows, 3 on each row for better spacing.
9. Mention roles of each member below their name. (Lead Developer, Backend Developer, Code Reviewer)
10. Remove twitter, google and facebook buttons.
11. Make sure footer items are linked to correct sections of the page.
12. Replace "Company name" in footer with "Paying it forward | Re:Coded".

2022-02-28 15:39 UTC, Shrreya approved these changes

2022-02-28 15:59 UTC, merged